language: node_js
node_js: 
  - lts/*
cache:
  directories:
    - node_modules
  script:
    - npm run jest
after_success:
  - npm run build
  - mv dist vue && find vue -type f -exec curl -u ${SFTP_USER}:${SFTP_PASSWORD} --ftp-create-dirs -T {} ftp://ftp.jaakkouusitalo.fi/{} \;