language: node_js
node_js: 
  - lts/*
cache:
  directories:
    - node_modules
  script:
    - npm run jest
after_success:
  - npm run build
  - find . \( -path "./dist/*" -o \) -prune -o -name "*" -print -exec curl --ftp-create-dirs -T {} ftp://jaakkouusitalo.fi/vue/ --user ${SFTP_USER}:${SFTP_PASSWORD} \;